# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](https://github.com/kritiAT/lab-neural-networks/blob/master/your-code/tttboard.jpg?raw=1)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd
import numpy as np

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

In [2]:
df = pd.read_csv('tic-tac-toe.csv')
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
print(df.shape)
df.isna().sum().sum()

(958, 10)

np.int64(0)

In [4]:
df = df.replace({'b' : 0, 'x' : 1, 'o' : 2})
df.head()

/tmp/ipykernel_33574/505125495.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'b' : 0, 'x' : 1, 'o' : 2})

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   1   1   1   1   2   2   1   2   2   True
1   1   1   1   1   2   2   2   1   2   True
2   1   1   1   1   2   2   2   2   1   True
3   1   1   1   1   2   2   2   0   0   True
4   1   1   1   1   2   2   0   2   0   True

In [5]:
features = df.drop(columns='class')
target = df['class']

features_norm = (features - features.mean()) / features.std()
features_norm.head()

,TL,TM,TR,ML,MM,MR,BL,BM,BR
0,-0.183675,-0.10789,-0.183675,-0.10789,1.163573,1.184095,-0.183675,1.184095,1.169866
1,-0.183675,-0.10789,-0.183675,-0.10789,1.163573,1.184095,1.169866,-0.107890,1.169866
2,-0.183675,-0.10789,-0.183675,-0.10789,1.163573,1.184095,1.169866,1.184095,-0.183675
3,-0.183675,-0.10789,-0.183675,-0.10789,1.163573,1.184095,1.169866,-1.399876,-1.537216
4,-0.183675,-0.10789,-0.183675,-0.10789,1.163573,1.184095,-1.537216,1.184095,-1.537216

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [6]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(features_norm, target, test_size=0.3, random_state=42)

In [7]:
model = Sequential()
model.add(Dense(50, activation='relu', input_shape=(features_norm.shape[1],)))
model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

# compile model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 50)             │           500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │           102 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,152 (12.31 KB)

 Trainable params: 3,152 (12.31 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.fit(X_train, y_train, epochs=20, verbose=1, validation_data=(X_test, y_test))

Epoch 1/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.5269 - loss: 0.7140 - val_accuracy: 0.6736 - val_loss: 0.6214
Epoch 2/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6627 - loss: 0.6087 - val_accuracy: 0.7014 - val_loss: 0.5830
Epoch 3/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6940 - loss: 0.5797 - val_accuracy: 0.7049 - val_loss: 0.5665
Epoch 4/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7299 - loss: 0.5590 - val_accuracy: 0.7222 - val_loss: 0.5501
Epoch 5/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7328 - loss: 0.5417 - val_accuracy: 0.7257 - val_loss: 0.5272
Epoch 6/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7343 - loss: 0.5231 - val_accuracy: 0.7222 - val_loss: 0.5139
Epoch 7/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7597 - loss: 0.5079 - val_accuracy: 0.7396 - val_loss: 0.4959
Epoch 8/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7642 - loss: 0.4843 - val_accuracy: 0.7222 - val_loss: 0.4836
Epoch 9/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.4635 - val_accuracy: 0.7500 - val_loss: 0.4708
Epoch 10/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7985 - loss: 0.4412 - val_accuracy: 0.7674 - val_loss: 0.4545
Epoch 11/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8000 - loss: 0.4222 - val_accuracy: 0.7778 - val_loss: 0.4410
Epoch 12/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8239 - loss: 0.4015 - val_accuracy: 0.7917 - val_loss: 0.4235
Epoch 13/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8313 - loss: 0.3834 - val_accuracy: 0.8090 - val_loss: 0.4129
Epoch 14/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8448 - loss: 0.3629 - val_accuracy: 0.7986 - val_loss: 0.4028
Epoch 15/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8672 - loss: 0.3477 - val_accuracy: 0.8160 - val_loss: 0.3888
Epoch 16/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8776 - loss: 0.3304 - val_accuracy: 0.8056 - val_loss: 0.3864
Epoch 17/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3169 - val_accuracy: 0.8264 - val_loss: 0.3770
Epoch 18/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8985 - loss: 0.2986 - val_accuracy: 0.8403 - val_loss: 0.3630
Epoch 19/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8896 - loss: 0.2859 - val_accuracy: 0.8333 - val_loss: 0.3583
Epoch 20/20
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8910 - loss: 0.2758 - val_accuracy: 0.8438 - val_loss: 0.3568

In [9]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.3568304479122162
Test accuracy: 0.84375

In [10]:
model.save('tic-tac-toe.keras')
#loaded_model = keras.saving.loaded_model('tic-tac-toe.model')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [11]:
loaded_model = keras.models.load_model('tic-tac-toe.keras')

In [12]:
X_test_random = X_test.sample(50, random_state=42)
y_test_random = y_test[X_test_random.index]

In [13]:
y_pred_r = np.argmax(loaded_model.predict(X_test_random), axis=1)

print('Accuracy : ', accuracy_score(y_test_random, y_pred_r))
print('F1 score : ', f1_score(y_test_random, y_pred_r))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Accuracy :  0.84
F1 score :  0.8620689655172413

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [14]:
model_2 = Sequential()
model_2.add(Dense(50, activation='relu', input_shape=(features_norm.shape[1],)))
model_2.add(Dense(50, activation='relu'))
model_2.add(Dense(50, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

# compile model_2
my_opt = Adam(learning_rate=0.01)
model_2.compile(optimizer=my_opt, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_2.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 50)             │           500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 50)             │         2,550 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 2)              │           102 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,702 (22.27 KB)

 Trainable params: 5,702 (22.27 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model_2.fit(X_train, y_train, epochs=30, verbose=1, validation_data=(X_test, y_test))

Epoch 1/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6776 - loss: 0.5976 - val_accuracy: 0.7118 - val_loss: 0.5098
Epoch 2/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7627 - loss: 0.4832 - val_accuracy: 0.7812 - val_loss: 0.4685
Epoch 3/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8299 - loss: 0.3791 - val_accuracy: 0.7986 - val_loss: 0.4010
Epoch 4/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8701 - loss: 0.3078 - val_accuracy: 0.8472 - val_loss: 0.3315
Epoch 5/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9179 - loss: 0.2182 - val_accuracy: 0.8160 - val_loss: 0.4352
Epoch 6/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9119 - loss: 0.2157 - val_accuracy: 0.8576 - val_loss: 0.3000
Epoch 7/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9463 - loss: 0.1464 - val_accuracy: 0.8368 - val_loss: 0.3578
Epoch 8/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9567 - loss: 0.1143 - val_accuracy: 0.8958 - val_loss: 0.2815
Epoch 9/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9612 - loss: 0.0822 - val_accuracy: 0.8819 - val_loss: 0.2922
Epoch 10/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9716 - loss: 0.0773 - val_accuracy: 0.8924 - val_loss: 0.3428
Epoch 11/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9851 - loss: 0.0608 - val_accuracy: 0.9132 - val_loss: 0.2000
Epoch 12/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9896 - loss: 0.0336 - val_accuracy: 0.9132 - val_loss: 0.2139
Epoch 13/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9940 - loss: 0.0219 - val_accuracy: 0.9062 - val_loss: 0.2278
Epoch 14/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9985 - loss: 0.0121 - val_accuracy: 0.9236 - val_loss: 0.2401
Epoch 15/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9970 - loss: 0.0123 - val_accuracy: 0.8819 - val_loss: 0.4779
Epoch 16/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9866 - loss: 0.0413 - val_accuracy: 0.9167 - val_loss: 0.2897
Epoch 17/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9746 - loss: 0.0715 - val_accuracy: 0.8819 - val_loss: 0.4782
Epoch 18/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9701 - loss: 0.0843 - val_accuracy: 0.8750 - val_loss: 0.3852
Epoch 19/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9493 - loss: 0.1373 - val_accuracy: 0.8368 - val_loss: 0.4472
Epoch 20/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9388 - loss: 0.1554 - val_accuracy: 0.8750 - val_loss: 0.2843
Epoch 21/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9791 - loss: 0.0650 - val_accuracy: 0.8924 - val_loss: 0.2557
Epoch 22/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9910 - loss: 0.0280 - val_accuracy: 0.9097 - val_loss: 0.2232
Epoch 23/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9955 - loss: 0.0119 - val_accuracy: 0.9271 - val_loss: 0.1989
Epoch 24/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9955 - loss: 0.0242 - val_accuracy: 0.9375 - val_loss: 0.1977
Epoch 25/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9910 - loss: 0.0340 - val_accuracy: 0.9097 - val_loss: 0.2471
Epoch 26/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9955 - loss: 0.0140 - val_accuracy: 0.9167 - val_loss: 0.2332
Epoch 27/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9925 - loss: 0.0228 - val_accuracy: 0.9097 - val_loss: 0.2343
Epoch 28/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9925 - loss: 0.0194 - val_accuracy: 0.9097 - val_loss: 0.2512
Epoch 29/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9970 - loss: 0.0213 - val_accuracy: 0.9167 - val_loss: 0.2158
Epoch 30/30
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9925 - loss: 0.0177 - val_accuracy: 0.9132 - val_loss: 0.2450

In [16]:
score_2 = model_2.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score_2[0])
print('Test accuracy:', score_2[1])

Test loss: 0.24502049386501312
Test accuracy: 0.9131944179534912

In [17]:
y_pred_r_2 = np.argmax(model_2.predict(X_test_random), axis=1)

print('Accuracy : ', accuracy_score(y_test_random, y_pred_r_2))
print('F1 score : ', f1_score(y_test_random, y_pred_r_2))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Accuracy :  0.92
F1 score :  0.9354838709677419

**Which approach(es) did you find helpful to improve your model performance?**

In [18]:
print('Difference in Test loss:', score_2[0] - score[0])
print('Difference in Test accuracy:', score_2[1] - score[1])

Difference in Test loss: -0.11180995404720306
Difference in Test accuracy: 0.06944441795349121

- Adding more layers and adjusting the learning rate improved the model performance.